### ISSUE TITLE
Gravação

### ISSUE THREAD

**Issue by fchevitarese** [lidimayra/raspagem-de-dados-fatec#5]
Gostaria de sugerir que vocês fizessem a gravação para quem não está ou não tem condição de estar no local onde acontecerá o evento! :)

Parabéns pela iniciativa! :+1:

**Comment by lidimayra** [comment]
Oi @fchevitarese, muito obrigada!! :smiley: só em saber que você teria interesse em assistir a uma gravação contendo o nosso trabalho, ficamos muito muito felizes!!! :confetti_ball: 

Vamos conversar aqui pra ver se rola agilizarmos isso!

**Comment by fchevitarese** [comment]
Legal!! Eu já fiz alguns trampos de raspagem de dados, com python e com nodejs :)

É sempre importante saber mais ^^

**Comment by lidimayra** [comment]
Oi @fchevitarese, infelizmente não conseguimos gravar! :disappointed: 
Mas é algo que realmente gostaríamos, quem sabe em uma outra oportunidade...
