### ISSUE TITLE
Data do evento: Set ou Out ?

### ISSUE THREAD

**Issue by phsantosjr** [lidimayra/raspagem-de-dados-fatec#6]
Pessoal,
no site da FATEC, na página de inscrição, não tem disponíveis as datas para o workshop em Setembro, somente uma data em 05/10 as 16:00.
Qual a data correta ?
Se for em Setembro, como se inscrever ?
Obrigado

**Comment by lidimayra** [comment]
Oi @phsantosjr, obrigada por avisar!
Já conversamos com o administrativo da FATEC e agora as duas opções de datas estão liberadas, dias 4 e 5 de setembro. Pode se inscrever por [aqui](http://www.fatecjd.edu.br/semtec/2017/inscr.php) 😉

**Comment by phsantosjr** [comment]
Obrigado, o README continua como setembro.
Infelizmente não poderei ir, estarei na PythonBR.
Boa sorte e sucesso !

**Comment by lidimayra** [comment]
@phsantosjr ahh o do site tava incorreto. O correto é setembro mesmo, semana que vem!
Muito obrigada! 😉

**Comment by lidimayra** [comment]
@phsantosjr muito obrigada pela presença, foi muito legal receber você por lá! :wink:
