### ISSUE TITLE
Múltiplas linguagens e métodos

### ISSUE THREAD

**Issue by MuriloViviani** [lidimayra/raspagem-de-dados-fatec#8]
Gostaria de propor que adicionássemos a este repositório, mais projetos relacionados a raspagem de dados, estes que poderiam ser feitos em outras linguagens, como C# por exemplo. Alem disso poderia ser válido adicionarmos novas técnicas para a realização da raspagem também!

Fico no aguardo de uma validação da ideia

**Comment by lidimayra** [comment]
Fazer isso aqui acho um pouco desorganizado e fora do nosso escopo. Mas sugiro a criação de diferentes repositórios para diferentes ambientes... adoraria, inclusive! :heart:
